name: xvitamins
description: 1xVitamins:Diary

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_generator: ^2.0.0
  flutter_screenutil: ^5.6.0
  flutter_svg_provider: ^1.0.3
  table_calendar: ^3.0.8
  flutter_svg: ^1.1.6
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.7
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  persistent_bottom_nav_bar_v2: ^4.2.6
  flutter_gen_runner: ^5.1.0+1
  page_transition: ^2.0.9
  very_good_analysis: ^3.1.0
  build_runner: ^2.3.2
  d_chart: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: InterSemi
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: InterRegular
      fonts:
            - asset: assets/fonts/Inter-Regular.ttf
    - family: InterBold
      fonts:
            - asset: assets/fonts/Inter-Bold.ttf

